# Numpy

Numpy is a library which provides support for large, homogenous, multi-dimensional arrays and matrices.

In [4]:
# import numpy
import numpy as np

## Creating Arrays in Numpy

### Creating an array from a list

In [2]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [6]:
arr1 = np.array(list1)
arr1

array([20, 40, 60])

In [7]:
type(arr1)

numpy.ndarray

### Using arange to create an array

The difference between array() and arange() is that array() takes in a list and turns it into an array, whereas arange creates an array from a range of numbers.

In [9]:
arr2 = np.arange(10, 20, 1) # Start, Stop, Step
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays

### Combining two list - Two-dimensional arrays

When we combine array stogether, we can add dimensions. Combining two arrays gives us a 2d array!

This creates a matrix for us on which we can perform matrix operations.

In [12]:
# Let's create a new list to join onto the first list
list2 = [40, 50, 60]

# Join the lists
list3 = [list1, list2]

# Create an array out of the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# Let's find the shape of that array
# We have a 2d array with 2 elemnts in the first instance and 3 in the second
arr3.shape

(2, 3)

### Three-dimensional arrays

In [21]:
arr3dim = np.array(
    [[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]]
      )
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [25]:
arr3dim.shape

(2, 2, 3)

## Using Arrays and Scalars

Numpy arrays (or ndarray) allow us to perform matrix operations.

In [29]:
# For example, we can use simple multiplication
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [32]:
# We can actually multiply an array with another array!

# Create a new array with the same size as arr1
arr11 = np.array(list2)

#Multiply the arrays, what will happen?
arr1 * arr11

array([ 400, 1000, 1800])

&#x2757; &#x2757; &#x2757; Important: you cannot multiply arrays of different shapes.

You can however multiply ararys of different dimensions:

In [35]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

Below are some exercises:

Create ndarrays of the following sizes:
One dimensional array with 12 elements (12,)
Two dimensional array size (3, 4)
Three dimensional array size (2, 5, 4)
Check the size of your ndarray to ensure it is correct

In [40]:
oned_array = np.arange(0,12)
oned_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
twod_array = numpy.ones((3,4))
twod_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
threed_array = numpy.zeros((2,5,4))
threed_array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Accessing the values inside ndarrays

Let's take arr3 as our example, this was a 2d array. 

In [51]:
# How can we access the 60?
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
arr3[1,2]

np.int64(60)

In [55]:
# How can I get the bottom "row" of this ndarray?
arr3[1]

array([40, 50, 60])

In [61]:
# How about the last column?
arr3[:,2]

array([30, 60])

### Statistical functions and arrays

There are a number of builtin statistical functions we can use with numpy

In [73]:
# Finding the sum of all values
arr3.sum()

np.int64(210)

In [64]:
arr3.sum(0)

array([50, 70, 90])

In [67]:
arr3.sum(1)

array([ 60, 150])

In [70]:
# Finding the mean
arr3.mean()

np.float64(35.0)

In [71]:
# Finding Standard Deviation
arr3.std()

np.float64(17.07825127659933)

### Iterating through ndarrays

Simplest way is to use a simple loop

In [74]:
# For a 1d array
for x in arr1:
    print(x)

10
20
30


In [76]:
# How about for an n-dimensional array? Use nested loops
for dim in arr3:
    for num in dim:
         print(num)

10
20
30
40
50
60


In [77]:
# There is another way! we can use nditer
# This can be used in simple scenarios, but also very complex ones
# It tensd to be much cleaner for nested loops
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


### Saving and loading in numpy

In [78]:
# To save an array as a file
np.save("new", arr3)

In [79]:
# load the file
np.load("new.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [80]:
# Saving as a txt
np.savetxt("new.txt", arr3, delimiter=",")