# Numpy

Numpy is a library which provides support for large, homogenous, multi-dimensional arrays and matrices.

In [4]:
# import numpy
import numpy as np

## Creating Arrays in Numpy

### Creating an array from a list

In [2]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [6]:
arr1 = np.array(list1)
arr1

array([20, 40, 60])

In [7]:
type(arr1)

numpy.ndarray

### Using arange to create an array

The difference between array() and arange() is that array() takes in a list and turns it into an array, whereas arange creates an array from a range of numbers.

In [9]:
arr2 = np.arange(10, 20, 1) # Start, Stop, Step
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays

### Combining two list - Two-dimensional arrays

When we combine array stogether, we can add dimensions. Combining two arrays gives us a 2d array!

This creates a matrix for us on which we can perform matrix operations.

In [12]:
# Let's create a new list to join onto the first list
list2 = [40, 50, 60]

# Join the lists
list3 = [list1, list2]

# Create an array out of the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# Let's find the shape of that array
# We have a 2d array with 2 elemnts in the first instance and 3 in the second
arr3.shape

(2, 3)

### Three-dimensional arrays